use std::collections::HashMap;
use crate::module2_ast::TranslationUnitAST;
use crate::data_stores::interprocedural_summaries::{InterproceduralSummaries, OwnershipKind};
use crate::module5_codegen::ownership_infer::FunctionOwnershipMap;

/// 0.5.2 Rust Source Synthesizer
/// Synthesizes candidate Rust source code (.rs) from AST, D1, D2, and inferred ownership classifications.
pub fn synthesize_rust_code(
    tu_ast: &TranslationUnitAST,
    ownership_maps: &HashMap<String, FunctionOwnershipMap>,
    _summaries: &InterproceduralSummaries,
) -> String {
    let mut code = String::new();

    code.push_str("// ========================================================\n");
    code.push_str("// Candidate Rust Code Generated by C2SafeRust-LLM\n");
    code.push_str("// ========================================================\n\n");

    // 1. Synthesize Enums (from transformed C unions)
    for union_def in &tu_ast.unions {
        code.push_str(&format!("#[derive(Debug, Clone)]\npub enum {}Enum {{\n", capitalize(&union_def.name)));
        for variant in &union_def.variants {
            let rust_type = map_c_type_to_rust(&variant.field_type);
            code.push_str(&format!("    {}({}),\n", capitalize(&variant.field_name), rust_type));
        }
        code.push_str("}\n\n");
    }

    // 2. Synthesize Structs
    for struct_def in &tu_ast.structs {
        code.push_str(&format!("#[derive(Debug, Clone)]\npub struct {} {{\n", struct_def.name));
        for (f_name, f_type) in &struct_def.fields {
            let rust_type = map_c_type_to_rust(f_type);
            code.push_str(&format!("    pub {}: {},\n", f_name, rust_type));
        }
        code.push_str("}\n\n");
    }

    // 3. Synthesize Functions
    for func in &tu_ast.functions {
        if func.name == "__attribute__" {
            continue; // Skip preprocessor internal attribute functions
        }

        let ret_type = map_c_type_to_rust(&func.return_type);
        let ret_clause = if ret_type == "()" {
            String::new()
        } else {
            format!(" -> {}", ret_type)
        };

        let mut param_strs = Vec::new();
        if let Some(own_map) = ownership_maps.get(&func.name) {
            for param in &func.parameters {
                let own_kind = own_map.variable_ownership.get(&param.name).unwrap_or(&OwnershipKind::SharedBorrow);
                let rust_type = format_rust_parameter_type(&param.c_type, param.pointer_depth, own_kind);
                param_strs.push(format!("{}: {}", param.name, rust_type));
            }
        }

        code.push_str(&format!("pub fn {}({}){} {{\n", func.name, param_strs.join(", "), ret_clause));

        // Synthesize function body lines
        for line in func.body_code.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed == "{" || trimmed == "}" {
                continue;
            }
            let rust_line = translate_c_line_to_rust(trimmed);
            code.push_str(&format!("    {}\n", rust_line));
        }

        code.push_str("}\n\n");
    }

    code
}

fn format_rust_parameter_type(c_type: &str, depth: usize, kind: &OwnershipKind) -> String {
    let base_rust = map_c_type_to_rust(c_type);

    match kind {
        OwnershipKind::UniqueHeapOwner => format!("Box<{}>", base_rust),
        OwnershipKind::MutableBorrow => {
            if depth >= 2 {
                format!("&mut &mut {}", base_rust)
            } else {
                format!("&mut {}", base_rust)
            }
        }
        OwnershipKind::SharedBorrow => {
            if depth > 0 {
                format!("&{}", base_rust)
            } else {
                base_rust
            }
        }
        OwnershipKind::HeapArray => format!("Vec<{}>", base_rust),
        OwnershipKind::ConservativeFallback => format!("Option<Box<{}>>", base_rust),
    }
}

fn map_c_type_to_rust(c_type: &str) -> String {
    let clean = c_type.trim();
    match clean {
        "int" => "i32".to_string(),
        "char" => "u8".to_string(),
        "float" => "f32".to_string(),
        "double" => "f64".to_string(),
        "void" => "()".to_string(),
        "long" => "i64".to_string(),
        "short" => "i16".to_string(),
        _ => clean.to_string(),
    }
}

fn translate_c_line_to_rust(line: &str) -> String {
    let mut rust_line = line.to_string();

    // Replace C types with Rust types
    rust_line = rust_line.replace("int ", "let mut ");
    rust_line = rust_line.replace("char ", "let mut ");
    rust_line = rust_line.replace("float ", "let mut ");
    rust_line = rust_line.replace("double ", "let mut ");
    rust_line = rust_line.replace("NULL", "std::ptr::null_mut()");

    // Clean trailing semicolons format
    if !rust_line.ends_with(';') && !rust_line.ends_with('{') && !rust_line.ends_with('}') {
        rust_line.push(';');
    }

    rust_line
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::module2_ast::ast_parser::{FunctionAST, ParameterAST};

    #[test]
    fn test_rust_code_synthesis() {
        let tu_ast = TranslationUnitAST {
            functions: vec![FunctionAST {
                name: "swap".to_string(),
                return_type: "void".to_string(),
                parameters: vec![
                    ParameterAST {
                        name: "a".to_string(),
                        c_type: "int".to_string(),
                        pointer_depth: 2,
                        is_union: false,
                    },
                    ParameterAST {
                        name: "b".to_string(),
                        c_type: "int".to_string(),
                        pointer_depth: 2,
                        is_union: false,
                    },
                ],
                body_code: "int *temp = *a;\n*a = *b;\n*b = temp;".to_string(),
                call_sites: vec![],
            }],
            unions: vec![],
            structs: vec![],
        };

        let mut ownership = HashMap::new();
        let mut swap_map = FunctionOwnershipMap {
            function_name: "swap".to_string(),
            variable_ownership: HashMap::new(),
        };
        swap_map.variable_ownership.insert("a".to_string(), OwnershipKind::MutableBorrow);
        swap_map.variable_ownership.insert("b".to_string(), OwnershipKind::MutableBorrow);
        ownership.insert("swap".to_string(), swap_map);

        let summaries = InterproceduralSummaries::new();

        let generated = synthesize_rust_code(&tu_ast, &ownership, &summaries);
        assert!(generated.contains("pub fn swap(a: &mut &mut i32, b: &mut &mut i32)"));
    }
}
